"""empty message

Revision ID: 25e6f8768a5e
Revises: 9a5dae2b0cb7
Create Date: 2017-03-04 17:52:31.994678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e6f8768a5e'
down_revision = '9a5dae2b0cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('middle_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent')
    # ### end Alembic commands ###
