"""empty message

Revision ID: f4d24cb262e2
Revises: 3bfb846d37eb
Create Date: 2017-04-13 13:11:59.547675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d24cb262e2'
down_revision = '3bfb846d37eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_group',
    sa.Column('parent_group', sa.Integer(), nullable=False),
    sa.Column('child_group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_group'], ['group.id'], ),
    sa.ForeignKeyConstraint(['parent_group'], ['group.id'], ),
    sa.PrimaryKeyConstraint('parent_group', 'child_group')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_group')
    # ### end Alembic commands ###
